import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { Resend } from 'resend'
import { searchBrave, extractPricesFromResults, computeAveragePrice } from '@/lib/brave/search'
import { evaluateProductAlerts } from '@/lib/pricing/evaluate-alerts'

export const runtime = 'nodejs'

export async function POST(req: NextRequest) {
  // T-11-12: CRON_SECRET check — 500 if undefined (misconfiguration), 401 if mismatch
  if (!process.env.CRON_SECRET) {
    return NextResponse.json({ error: 'CRON_SECRET not configured' }, { status: 500 })
  }
  const secret = req.headers.get('x-cron-secret')
  if (secret !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    // T-11-13: Service role key — server-only, bypasses RLS
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    )
    const resend = new Resend(process.env.RESEND_API_KEY)

    // Fetch all monitored products joined with their product data.
    const { data: monRows, error: monErr } = await supabase
      .from('pricing_monitor_products')
      .select('company_id, products(id, name, category, selling_price)')

    if (monErr) {
      console.error('[pricing-alerts] fetch monitored products error:', monErr)
      return NextResponse.json({ error: 'Failed to fetch monitored products' }, { status: 500 })
    }

    type Joined = {
      company_id: string
      products: { id: string; name: string | null; category: string | null; selling_price: number | null } | null
    }
    const monitored = ((monRows ?? []) as Joined[])
      .map((r) => ({
        company_id: r.company_id,
        product_id: r.products?.id ?? '',
        name: r.products?.name ?? 'product',
        category: (r.products?.category ?? '').trim(),
        selling_price: r.products?.selling_price ?? 0,
      }))
      .filter((m) => m.category.length > 0 && m.selling_price > 0)

    // One Brave call per distinct category (preserve the 200-call cap).
    const MAX_BRAVE_CALLS = 200
    const categories = Array.from(new Set(monitored.map((m) => m.category))).slice(0, MAX_BRAVE_CALLS)

    const marketAvgByCategory: Record<string, number> = {}
    for (const category of categories) {
      try {
        const results = await searchBrave(`${category} price india wholesale`, 10)
        const avg = computeAveragePrice(extractPricesFromResults(results))
        if (avg !== null) marketAvgByCategory[category] = avg
      } catch (braveErr) {
        console.error(`[pricing-alerts] Brave error for "${category}":`, braveErr)
      }
    }

    const alertsByCompany = evaluateProductAlerts(monitored, marketAvgByCategory)

    let alertsSent = 0
    for (const [companyId, alerts] of alertsByCompany) {
      const { data: adminRows } = await supabase
        .from('company_users')
        .select('user_id, companies(name)')
        .eq('company_id', companyId)
        .eq('role', 'admin')
        .limit(1)
      const adminUser = adminRows?.[0]
      if (!adminUser) continue

      const { data: authUser } = await supabase.auth.admin.getUserById(adminUser.user_id)
      const adminEmail = authUser?.user?.email
      if (!adminEmail) continue

      const companyName = (adminUser.companies as { name?: string } | null)?.name ?? 'Your company'
      const lines = alerts.map(
        (a) =>
          `  • ${a.name} (${a.category}): yours ₹${a.companyPrice.toFixed(2)} vs market ₹${a.marketAvg.toFixed(2)} (${a.deltaPct.toFixed(1)}% off)`,
      )

      const { error: emailError } = await resend.emails.send({
        from: process.env.RESEND_FROM_EMAIL!,
        to: adminEmail,
        subject: `Pricing alert: ${alerts.length} product${alerts.length === 1 ? '' : 's'} need a look`,
        text: [
          `Hello ${companyName},`,
          '',
          'These monitored products are priced more than 10% away from the market:',
          '',
          ...lines,
          '',
          'Review them at:',
          `${process.env.NEXT_PUBLIC_SITE_URL ?? 'https://invoiceiq.in'}/dashboard/settings/pricing-alerts`,
          '',
          "This alert was generated by InvoiceIQ's automated pricing monitor.",
        ].join('\n'),
      })
      if (emailError) {
        console.error(`[pricing-alerts] Resend error company=${companyId}:`, emailError)
      } else {
        alertsSent += alerts.length
      }
    }

    return NextResponse.json(
      { categories_checked: Object.keys(marketAvgByCategory).length, alerts_sent: alertsSent },
      { status: 200 },
    )
  } catch (err) {
    console.error('[pricing-alerts] unexpected error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
